"""The action table, against the plans the mission planner actually emits.

``examples/sample_*.xml`` are three real plans generated by the upstream GPT
mission planner for the three-robot run, one per robot. They are the reason
this module exists: every one of them writes a sampling objective as *enter the
aisle, approach the tree, sample it*, with the aisle move sitting outside the
``RetryUntilSuccessful`` that wraps the other two. Nothing in this system could
see that relationship before, so a task handed to another robot arrived without
the part that gets the robot there.

The table is checked against the schema rather than against a list here, so a
tenth action in ``ActionGroup`` is a failure in this file rather than a leaf
that silently means nothing.
"""

import os
import sys

import pytest
from lxml import etree

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from amiga_ros2_agents.mission import ontology, orchard  # noqa: E402
from amiga_ros2_agents.verification import promela  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXAMPLES = os.path.join(REPO, "amiga_ros2_behavior_tree", "examples")
SCHEMA = os.path.join(REPO, "amiga_ros2_behavior_tree", "schemas", "amiga_btcpp.xsd")

#: The three-robot demo set, and the aisle each objective is reached from --
#: read off the plans themselves, which is the agreement being pinned.
PLANNER_PLANS = {
    "sample_20_64.xml": {"20": "2", "64": "4"},
    "sample_22_66.xml": {"22": "2", "66": "4"},
    "sample_24_68.xml": {"24": "2", "68": "4"},
}


def example(name: str):
    with open(os.path.join(EXAMPLES, name), "rb") as handle:
        return etree.fromstring(handle.read())


@pytest.fixture(scope="module")
def orchard_map():
    """The real orchard, out of the mission binary the planner produced."""
    return orchard.parse(_orchard_frame("sample_20_64.bin"))


# ==========================================================================
# The table is closed against the schema
# ==========================================================================


def test_the_table_describes_exactly_the_schemas_actions():
    """Both directions, and both are failures worth having.

    An action in the schema with no row here is a leaf the planner may emit and
    nothing understands -- it would establish nothing, so a plan containing it
    would verify vacuously. A row with no schema action is a rule about
    something that cannot appear in a plan, which the next reader will believe.
    """
    ok, reason = ontology.covers(promela.action_pool(SCHEMA))
    assert ok, reason


def test_every_action_leaf_can_be_advanced():
    """No element of the vocabulary raises when a walk reaches it."""
    for tag in promela.action_pool(SCHEMA):
        assert tag in ontology.TABLE


# ==========================================================================
# The chain the planner writes
# ==========================================================================


@pytest.mark.parametrize("name", sorted(PLANNER_PLANS))
def test_the_planners_own_plans_break_no_precondition(name, orchard_map):
    """The check that gates them, run over the real thing.

    All three write the objective inside a ``RetryUntilSuccessful`` -- the move
    and the sample together -- which the arbiter's old sibling-scoped check
    happened to accept. The one before this rewrite did not accept every shape
    the planner emits, and this is the file that would have caught it.
    """
    assert ontology.violations(example(name), orchard_map) == []


@pytest.mark.parametrize("name", sorted(PLANNER_PLANS))
def test_reaching_a_tree_expects_that_trees_aisle(name, orchard_map):
    """The relationship the whole design turns on.

    Each ``MoveToTreeID`` expects to be in an aisle that reaches that tree, and
    each is preceded by the ``MoveToAisleHead`` that establishes it -- so
    nothing is reported missing. That agreement is not arranged here: the aisle
    ids come from the orchard dump and the plan was written by a model that
    never saw this table.

    A row sits between two lanes, so the expectation names both and the aisle
    the planner picked has to be one of them. Pinning it to a single id would
    say a plan that went round to the far side of a blocked row had got the
    aisle wrong, which is the opposite of true.
    """
    state = ontology.State()
    for element in ontology.actions_in(example(name)):
        step, state = ontology.advance(state, element, orchard_map)
        if step.proposition == ontology.OBJECTIVE:
            need = step.needs[0]
            assert need.kind == ontology.IN_AISLE
            assert need.strength == ontology.EXPECTED
            leaf = element.get("name")
            assert step.missing == (), f"{leaf} is missing {step.missing}"
            chosen = PLANNER_PLANS[name][element.get("id")]
            assert chosen in need.arg, (
                f"{leaf}: the planner entered aisle {chosen}, which does not "
                f"reach tree {element.get('id')} ({need.arg})"
            )


def test_a_tree_move_without_its_aisle_move_is_allowed_but_noted(orchard_map):
    """Expected, not required -- the distinction the design rests on.

    ``sample_leafs.xml`` reaches both its trees with no aisle move anywhere in
    the plan, and it runs: navigation routes there regardless. Refusing it
    would reject every mission this fleet has ever flown. What the expectation
    buys is knowing the step is *absent*, which is what a planner can be told
    and what a rebuilt task can supply.
    """
    state = ontology.State()
    noted = []
    for element in ontology.actions_in(example("sample_leafs.xml")):
        step, state = ontology.advance(state, element, orchard_map)
        assert step.violation == "", "a missing aisle move must not refuse a plan"
        noted.extend(str(need) for need in step.missing)
    assert noted, "the absent aisle moves should be visible to a planner"
    assert all(note.startswith(ontology.IN_AISLE) for note in noted)


# ==========================================================================
# Position is exclusive, achievement latches
# ==========================================================================


def test_a_sample_binds_to_the_tree_the_robot_approached():
    """The leaf carries no location; the state is where it gets one."""
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    state = ontology.State()
    for element in ontology.actions_in(plan):
        step, state = ontology.advance(state, element)
    assert ontology.Fact(ontology.SAMPLED_TREE, "60") in state.facts


def test_driving_past_a_tree_is_not_being_at_it():
    """``approach_tree="false"`` is a waypoint, and sampling from one is wrong.

    The same line the arbiter's ``_objective_tree_ids`` draws. Without it a
    plan could satisfy "sample tree 60" by driving past it.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="false"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    assert "requires" in " ".join(ontology.violations(plan))


def test_leaving_for_the_aisle_head_ends_being_at_the_tree():
    """A prerequisite step is also a departure.

    Two of the planner's plans drive back out to the aisle head after sampling.
    A state that still claimed the robot was at the tree would let a later
    SampleLeaf bind to a tree the robot has driven away from.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<MoveToAisleHead name="out" id="6"/><SampleLeaf name="s"/></Sequence>'
    )
    assert ontology.violations(plan), "the sample has no tree to bind to"


def test_lining_up_at_a_tree_is_not_leaving_it():
    """A relative nudge and a turn are how a plan positions, not how it departs.

    Treating them as travel would make ``approach, nudge, sample`` an orphaned
    sample -- a reasonable plan the fleet would then refuse.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<MoveToRelativeLocation name="n" x="0.2" y="0.0"/>'
        b'<OrientRobotHeading name="t" absolute="false" yaw="0.1"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    assert ontology.violations(plan) == []


def test_having_sampled_a_tree_survives_driving_away():
    """Achievement latches; position does not. Same asymmetry promela encodes."""
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="s"/><MoveToAisleHead name="out" id="6"/></Sequence>'
    )
    state = ontology.State()
    for element in ontology.actions_in(plan):
        _, state = ontology.advance(state, element)
    assert ontology.Fact(ontology.SAMPLED_TREE, "60") in state.facts
    assert state.holding(ontology.AT_TREE) is None


# ==========================================================================
# Refusals and honest unknowns
# ==========================================================================


def test_a_bare_sample_is_refused_by_name():
    """``test_sample_leaf.xml`` is a bring-up rig: it samples nowhere.

    The reason names the element that would fix it rather than the predicate
    that failed, because the reason is handed back to the model that wrote the
    plan and a planner cannot emit an ``at_tree``.
    """
    problems = ontology.violations(example("test_sample_leaf.xml"))
    assert len(problems) == 1
    assert "TestSampleLeaf" in problems[0]
    assert "MoveToTreeID" in problems[0]


def test_a_move_with_no_id_is_a_defect_not_a_missing_prerequisite():
    """Nothing earlier in the plan could have fixed it, so it reads differently."""
    element = etree.fromstring(b'<MoveToTreeID name="v" approach_tree="true"/>')
    step, _ = ontology.advance(ontology.State(), element)
    assert step.defect
    assert "has no id" in step.violation


def test_an_unknown_aisle_is_an_unknown_and_not_a_guess(orchard_map):
    """No orchard means the expectation cannot be bound, never that it failed.

    Every caller treats an unknown aisle as advice it cannot give. A number
    invented here would be a robot sent down the wrong lane.
    """
    element = etree.fromstring(b'<MoveToTreeID name="v" id="60" approach_tree="true"/>')
    without, _ = ontology.advance(ontology.State(), element)
    with_map, _ = ontology.advance(ontology.State(), element, orchard_map)
    assert without.needs[0].arg == ""
    assert with_map.needs[0].arg == ("4", "5"), "both lanes that reach tree 60"


def test_a_control_node_is_not_an_action():
    with pytest.raises(ontology.OntologyError):
        ontology.advance(ontology.State(), etree.fromstring(b"<Sequence/>"))


# ==========================================================================
# Fallback: only what every branch agrees on
# ==========================================================================


def test_a_choice_keeps_only_what_both_branches_establish():
    left = ontology.State(frozenset({ontology.Fact(ontology.AT_TREE, "10")}))
    right = ontology.State(frozenset({ontology.Fact(ontology.AT_TREE, "60")}))
    assert left.merge(right).facts == frozenset()
    assert left.merge(left).facts == left.facts


# ==========================================================================
# Pruning what has already happened
# ==========================================================================


def test_objective_trees_binds_names_to_ids(orchard_map):
    """The names /bt/status_change actually reports, resolved to tree ids.

    The names are the planner's, not ours, and change whenever an example plan
    is regenerated -- so what is pinned is the binding, not the spelling: each
    SampleLeaf resolves to the tree the MoveToTreeID ahead of it approached.
    """
    plan = example("sample_20_64.xml")
    names = [el.get("name") for el in plan.iter("SampleLeaf")]
    expected = dict(zip(names, PLANNER_PLANS["sample_20_64.xml"]))
    assert ontology.objective_trees(plan, orchard_map) == expected


def test_a_harvested_tree_counts_as_done(orchard_map):
    """A harvest binds to its tree, and pruning removes it.

    Regression: the binding matched ``SampleLeaf`` alone, so on a harvest
    mission nothing ever entered the completed ledger. Every replan then
    redeployed a plan still containing finished trees, and the executor --
    which rebuilds from the root and re-ticks -- drove back and harvested them
    again. Only a robot that faulted saw it, because only a fault triggers the
    redeploy, which is what made it look robot-specific.
    """
    plan = example("harvest_aisle2.xml")

    bound = ontology.objective_trees(plan, orchard_map)
    harvests = [el.get("name") for el in plan.iter("HarvestFruit")]
    assert harvests, "fixture has no HarvestFruit to bind"
    assert set(bound) == set(harvests)

    done = bound[harvests[0]]
    pruned = ontology.prune_completed(plan, [done], orchard_map)
    assert done not in ontology.objective_trees(pruned, orchard_map).values()
    # The other tree is still there: pruning removes what is finished, not the
    # rest of the mission.
    assert len(list(pruned.iter("HarvestFruit"))) == len(harvests) - 1


def test_either_lane_that_reaches_a_tree_satisfies_the_expectation(orchard_map):
    """Going round to the far side of a blocked row is not an error.

    Tree 20 is worked from aisle 2 or aisle 3. The orchard's default answer is
    2, and a plan that enters 3 instead is answering something -- a lane
    blocked by a vehicle that will not move -- rather than getting the aisle
    wrong. Reporting it as unmet would feed the planner a finding telling it to
    go back to the lane it just failed in.
    """
    for aisle in ("2", "3"):
        plan = etree.fromstring(
            b'<root BTCPP_format="4" schema_location="schemas/amiga_btcpp.xsd">'
            b"<Mission>m</Mission><BehaviorTree ID=\"M\"><Sequence>"
            b'<MoveToAisleHead name="h" action_name="move_to_aisle_head" id="'
            + aisle.encode() + b'"/>'
            b'<MoveToTreeID name="v" action_name="follow_tree_id_waypoint"'
            b' id="20" approach_tree="true"/>'
            b'<SampleLeaf name="s" action_name="segment_leaves"/>'
            b"</Sequence></BehaviorTree></root>"
        )
        state = ontology.State()
        noted = []
        for element in ontology.actions_in(plan):
            step, state = ontology.advance(state, element, orchard_map)
            noted.extend(step.missing)
        assert noted == [], f"entering aisle {aisle} was reported as missing {noted}"


def test_a_lane_that_does_not_reach_the_tree_is_still_noted(orchard_map):
    """The expectation naming two lanes is not the same as naming none. Aisle 5
    does not run alongside row 2, so a plan entering it has not reached tree 20
    by any route, and that is worth saying."""
    plan = etree.fromstring(
        b'<root BTCPP_format="4" schema_location="schemas/amiga_btcpp.xsd">'
        b"<Mission>m</Mission><BehaviorTree ID=\"M\"><Sequence>"
        b'<MoveToAisleHead name="h" action_name="move_to_aisle_head" id="5"/>'
        b'<MoveToTreeID name="v" action_name="follow_tree_id_waypoint"'
        b' id="20" approach_tree="true"/>'
        b'<SampleLeaf name="s" action_name="segment_leaves"/>'
        b"</Sequence></BehaviorTree></root>"
    )
    state = ontology.State()
    noted = []
    for element in ontology.actions_in(plan):
        step, state = ontology.advance(state, element, orchard_map)
        noted.extend(step.missing)
    assert any(n.kind == ontology.IN_AISLE for n in noted)


def test_pruning_nothing_returns_the_plan_unchanged():
    plan = example("sample_20_64.xml")
    assert ontology.prune_completed(plan, set()) is plan


def test_a_completed_tree_and_its_retry_wrapper_are_removed(orchard_map):
    """Removing the objective must not leave an empty RetryUntilSuccessful.

    That is how every plan this fleet flies wraps a sample -- see
    PLANNER_PLANS above -- so a prune that only deleted the leaves would hand
    the model back a plan with a dangling, childless retry in it.
    """
    pruned = ontology.prune_completed(example("sample_20_64.xml"), {"20"}, orchard_map)
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"64"}
    retries = pruned.findall(".//RetryUntilSuccessful")
    assert len(retries) == 1, "tree 20's retry wrapper should have gone with it"
    assert retries[0].find(".//MoveToTreeID").get("id") == "64"


def test_pruning_leaves_no_empty_wrapper_behind(orchard_map):
    """The XSD failure that fired on every absorb in a live run.

    Grafting a won task wraps the plan's original leaves in a bare
    ``<Sequence>`` so the two halves stay separable. When the winner had
    already finished the work in that wrapper, pruning emptied it and left
    ``<Sequence/>`` in the plan -- which the XSD rejects, because a control
    node must hold at least one action.

    The plan the planner shows the model is the *pruned* one, so the model was
    handed XML that could not validate and every edit it returned inherited
    the fault: "LLM edit failed XSD validation -- not publishing", on every
    hand-off, costing the winner the one replan that would have re-derived the
    Wait its rebuild dropped.

    Both of the wrapper's objectives have to be finished for this to bite: with
    one still pending, ``_isolated_ancestor`` stops below the wrapper and the
    wrapper keeps a child. It is the aisle heads outliving the last tree that
    empty it.
    """
    plan = example("sample_20_64.xml")
    root_control = plan.find(".//BehaviorTree")[0]
    wrapper = etree.Element("Sequence")
    root_control.insert(0, wrapper)
    for element in list(root_control)[1:]:
        wrapper.append(element)
    absorbed = etree.SubElement(root_control, "Sequence", name="task_43808")
    etree.SubElement(
        absorbed,
        "MoveToTreeID",
        name="task_43808_visit_90",
        action_name="follow_tree_id_waypoint",
        id="90",
        approach_tree="true",
    )
    etree.SubElement(
        absorbed,
        "SampleLeaf",
        name="task_43808_sample_90",
        action_name="segment_leaves",
    )

    pruned = ontology.prune_completed(plan, {"20", "64"}, orchard_map)

    assert not [
        el for el in pruned.iter() if el.tag in ontology.CONTROLS and len(el) == 0
    ], "the emptied wrapper must go with its contents"
    assert etree.XMLSchema(etree.parse(SCHEMA)).validate(pruned), (
        "the pruned plan is what the model is asked to edit, so it has to be "
        "valid before the model ever sees it"
    )
    remaining = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining == {"90"}, "only the absorbed task is left to do"


def test_pruning_removes_both_halves_of_a_flat_objective(orchard_map):
    """The task amiga2 won and could not keep.

    A task won at auction is grafted as one flat Sequence -- aisle move,
    approach, sample, and whatever the planner added, all siblings. No ancestor
    holds the approach/sample pair alone, so the climb that normally finds a
    wrapper to delete has nowhere to go and returns the approach by itself.

    Pruning then removed the approach and left the SampleLeaf behind, and the
    arbiter's own precondition check rejected the plan for it: "<SampleLeaf>
    ... requires a preceding <MoveToTreeID approach_tree='true'>". Live, amiga2
    had sampled tree 20 from an earlier auction, won tree 26, and could not
    graft it -- the task bounced and had to be auctioned again.

    Only bites on a SECOND absorb: a robot's own objectives arrive wrapped in
    their own RetryUntilSuccessful and prune cleanly, which is why the first
    hand-off of a run always worked.
    """
    plan = etree.fromstring(
        b'<root BTCPP_format="4" schema_location="schemas/amiga_btcpp.xsd">'
        b"<Mission>sample leaves from tree 20</Mission>"
        b'<BehaviorTree ID="Main"><Sequence name="Mission">'
        b'<Sequence name="task_43808">'
        b'<MoveToAisleHead name="task_43808_aisle" action_name="move_to_aisle_head" id="2"/>'
        b'<MoveToTreeID name="task_43808_visit" action_name="follow_tree_id_waypoint"'
        b' id="20" approach_tree="true"/>'
        b'<SampleLeaf name="task_43808_sample" action_name="segment_leaves"/>'
        b'<Wait name="task_43808_wait" seconds="2.0"/>'
        b"</Sequence></Sequence></BehaviorTree></root>"
    )

    pruned = ontology.prune_completed(plan, {"20"}, orchard_map)

    assert pruned.find(".//MoveToTreeID") is None
    assert pruned.find(".//SampleLeaf") is None, (
        "a sample whose approach was pruned away has nothing establishing "
        "where the robot is standing"
    )
    assert ontology.violations(pruned, orchard_map) == []


def test_pruning_cascades_through_nested_wrappers(orchard_map):
    """A wrapper whose only child was itself emptied goes too, so one prune
    cannot leave a chain of hollow controls in the middle of a plan."""
    plan = example("sample_20_64.xml")
    root_control = plan.find(".//BehaviorTree")[0]
    outer = etree.SubElement(root_control, "Sequence", name="outer")
    inner = etree.SubElement(outer, "Sequence", name="inner")
    for child in list(root_control)[:-1]:
        inner.append(child)

    pruned = ontology.prune_completed(plan, {"20", "64"}, orchard_map)

    assert pruned.find('.//Sequence[@name="inner"]') is None
    assert pruned.find('.//Sequence[@name="outer"]') is None


def test_a_completed_trees_own_aisle_head_goes_with_it(orchard_map):
    """Tree 20's aisle (2) belongs to no other tree in this plan, so both its
    enter and exit MoveToAisleHead should go; tree 64's aisle (4) must stay."""
    pruned = ontology.prune_completed(example("sample_20_64.xml"), {"20"}, orchard_map)
    aisle_ids = [
        el.get("id")
        for el in ontology.actions_in(pruned)
        if el.tag == "MoveToAisleHead"
    ]
    assert aisle_ids == ["4", "4"]


def test_a_shared_aisle_head_survives_for_the_tree_still_pending():
    """Two trees in the same aisle: finishing one must not strand the other.

    A synthetic plan, because none of the real examples share an aisle -- the
    property this checks is that ``prune_completed`` looks at every remaining
    objective before deciding an aisle head is unneeded, not just the one
    being removed.
    """
    plan = etree.fromstring(
        b"<Sequence>"
        b'<MoveToAisleHead name="enter" id="6"/>'
        b'<MoveToTreeID name="v1" id="55" approach_tree="true"/>'
        b'<SampleLeaf name="sample_tree55"/>'
        b'<MoveToTreeID name="v2" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="sample_tree60"/>'
        b'<MoveToAisleHead name="exit" id="6"/>'
        b"</Sequence>"
    )
    # Both trees on the same lane, and that lane the only one that reaches
    # them: an edge row, where a tree has a lane on one side only.
    orchard_map = orchard.Orchard({55: (6,), 60: (6,)})
    pruned = ontology.prune_completed(plan, {"55"}, orchard_map)
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"60"}
    aisle_heads = [
        el for el in ontology.actions_in(pruned) if el.tag == "MoveToAisleHead"
    ]
    assert len(aisle_heads) == 2, "aisle 6 is still needed for tree 60"


def test_an_unknown_completed_tree_is_ignored(orchard_map):
    """A tree id that names nothing in the plan is not a defect to raise."""
    plan = example("sample_20_64.xml")
    pruned = ontology.prune_completed(plan, {"9999"}, orchard_map)
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"20", "64"}


def _orchard_frame(name: str) -> str:
    """The orchard JSON out of a mission binary: length-prefixed frame two."""
    import struct

    with open(os.path.join(EXAMPLES, name), "rb") as handle:
        data = handle.read()
    offset = 0
    frames = []
    while offset + 4 <= len(data):
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        offset += 4
        frames.append(data[offset : offset + length])
        offset += length
    return frames[1].decode()
