"""The action table, against the plans the mission planner actually emits.

``examples/aisle_sample_*.xml`` are three real plans generated by the upstream
GPT mission planner for the three-robot run, one per robot. They are the reason
this module exists: every one of them writes a sampling objective as *enter the
aisle, approach the tree, sample it*, with the aisle move sitting outside the
``RetryUntilSuccessful`` that wraps the other two. Nothing in this system could
see that relationship before, so a task handed to another robot arrived without
the part that gets the robot there.

The table is checked against the schema rather than against a list here, so a
tenth action in ``ActionGroup`` is a failure in this file rather than a leaf
that silently means nothing.
"""

import os
import sys

import pytest
from lxml import etree

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from amiga_ros2_agents.mission import ontology, orchard  # noqa: E402
from amiga_ros2_agents.verification import promela  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXAMPLES = os.path.join(REPO, "amiga_ros2_behavior_tree", "examples")
SCHEMA = os.path.join(REPO, "amiga_ros2_behavior_tree", "schemas", "amiga_btcpp.xsd")

#: The three-robot demo set, and the aisle each objective is reached from --
#: read off the plans themselves, which is the agreement being pinned.
PLANNER_PLANS = {
    "aisle_sample_10_60.xml": {"10": "10", "60": "6"},
    "aisle_sample_12_62.xml": {"12": "12", "62": "8"},
    "aisle_sample_14_64.xml": {"14": "14", "64": "10"},
}


def example(name: str):
    with open(os.path.join(EXAMPLES, name), "rb") as handle:
        return etree.fromstring(handle.read())


@pytest.fixture(scope="module")
def orchard_map():
    """The real orchard, out of the mission binary the planner produced."""
    return orchard.parse(_orchard_frame("aisle_sample_10_60.bin"))


# ==========================================================================
# The table is closed against the schema
# ==========================================================================


def test_the_table_describes_exactly_the_schemas_actions():
    """Both directions, and both are failures worth having.

    An action in the schema with no row here is a leaf the planner may emit and
    nothing understands -- it would establish nothing, so a plan containing it
    would verify vacuously. A row with no schema action is a rule about
    something that cannot appear in a plan, which the next reader will believe.
    """
    ok, reason = ontology.covers(promela.action_pool(SCHEMA))
    assert ok, reason


def test_every_action_leaf_can_be_advanced():
    """No element of the vocabulary raises when a walk reaches it."""
    for tag in promela.action_pool(SCHEMA):
        assert tag in ontology.TABLE


# ==========================================================================
# The chain the planner writes
# ==========================================================================


@pytest.mark.parametrize("name", sorted(PLANNER_PLANS))
def test_the_planners_own_plans_break_no_precondition(name, orchard_map):
    """The check that gates them, run over the real thing.

    All three write the objective inside a ``RetryUntilSuccessful`` -- the move
    and the sample together -- which the arbiter's old sibling-scoped check
    happened to accept. The one before this rewrite did not accept every shape
    the planner emits, and this is the file that would have caught it.
    """
    assert ontology.violations(example(name), orchard_map) == []


@pytest.mark.parametrize("name", sorted(PLANNER_PLANS))
def test_reaching_a_tree_expects_that_trees_aisle(name, orchard_map):
    """The relationship the whole design turns on.

    Each ``MoveToTreeID`` expects to be in the aisle the orchard puts that tree
    in, and each is preceded by the ``MoveToAisleHead`` that establishes it --
    so nothing is reported missing. That agreement is not arranged here: the
    aisle ids come from the orchard dump and the plan was written by a model
    that never saw this table.
    """
    state = ontology.State()
    expectations = {}
    for element in ontology.actions_in(example(name)):
        step, state = ontology.advance(state, element, orchard_map)
        if step.proposition == ontology.OBJECTIVE:
            need = step.needs[0]
            assert need.kind == ontology.IN_AISLE
            assert need.strength == ontology.EXPECTED
            leaf = element.get("name")
            assert step.missing == (), f"{leaf} is missing {step.missing}"
            expectations[element.get("id")] = need.arg
    assert expectations == PLANNER_PLANS[name]


def test_a_tree_move_without_its_aisle_move_is_allowed_but_noted(orchard_map):
    """Expected, not required -- the distinction the design rests on.

    ``sample_leafs.xml`` reaches both its trees with no aisle move anywhere in
    the plan, and it runs: navigation routes there regardless. Refusing it
    would reject every mission this fleet has ever flown. What the expectation
    buys is knowing the step is *absent*, which is what a planner can be told
    and what a rebuilt task can supply.
    """
    state = ontology.State()
    noted = []
    for element in ontology.actions_in(example("sample_leafs.xml")):
        step, state = ontology.advance(state, element, orchard_map)
        assert step.violation == "", "a missing aisle move must not refuse a plan"
        noted.extend(str(need) for need in step.missing)
    assert noted, "the absent aisle moves should be visible to a planner"
    assert all(note.startswith(ontology.IN_AISLE) for note in noted)


# ==========================================================================
# Position is exclusive, achievement latches
# ==========================================================================


def test_a_sample_binds_to_the_tree_the_robot_approached():
    """The leaf carries no location; the state is where it gets one."""
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    state = ontology.State()
    for element in ontology.actions_in(plan):
        step, state = ontology.advance(state, element)
    assert ontology.Fact(ontology.SAMPLED_TREE, "60") in state.facts


def test_driving_past_a_tree_is_not_being_at_it():
    """``approach_tree="false"`` is a waypoint, and sampling from one is wrong.

    The same line the arbiter's ``_objective_tree_ids`` draws. Without it a
    plan could satisfy "sample tree 60" by driving past it.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="false"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    assert "requires" in " ".join(ontology.violations(plan))


def test_leaving_for_the_aisle_head_ends_being_at_the_tree():
    """A prerequisite step is also a departure.

    Two of the planner's plans drive back out to the aisle head after sampling.
    A state that still claimed the robot was at the tree would let a later
    SampleLeaf bind to a tree the robot has driven away from.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<MoveToAisleHead name="out" id="6"/><SampleLeaf name="s"/></Sequence>'
    )
    assert ontology.violations(plan), "the sample has no tree to bind to"


def test_lining_up_at_a_tree_is_not_leaving_it():
    """A relative nudge and a turn are how a plan positions, not how it departs.

    Treating them as travel would make ``approach, nudge, sample`` an orphaned
    sample -- a reasonable plan the fleet would then refuse.
    """
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<MoveToRelativeLocation name="n" x="0.2" y="0.0"/>'
        b'<OrientRobotHeading name="t" absolute="false" yaw="0.1"/>'
        b'<SampleLeaf name="s"/></Sequence>'
    )
    assert ontology.violations(plan) == []


def test_having_sampled_a_tree_survives_driving_away():
    """Achievement latches; position does not. Same asymmetry promela encodes."""
    plan = etree.fromstring(
        b'<Sequence><MoveToTreeID name="v" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="s"/><MoveToAisleHead name="out" id="6"/></Sequence>'
    )
    state = ontology.State()
    for element in ontology.actions_in(plan):
        _, state = ontology.advance(state, element)
    assert ontology.Fact(ontology.SAMPLED_TREE, "60") in state.facts
    assert state.holding(ontology.AT_TREE) is None


# ==========================================================================
# Refusals and honest unknowns
# ==========================================================================


def test_a_bare_sample_is_refused_by_name():
    """``test_sample_leaf.xml`` is a bring-up rig: it samples nowhere.

    The reason names the element that would fix it rather than the predicate
    that failed, because the reason is handed back to the model that wrote the
    plan and a planner cannot emit an ``at_tree``.
    """
    problems = ontology.violations(example("test_sample_leaf.xml"))
    assert len(problems) == 1
    assert "TestSampleLeaf" in problems[0]
    assert "MoveToTreeID" in problems[0]


def test_a_move_with_no_id_is_a_defect_not_a_missing_prerequisite():
    """Nothing earlier in the plan could have fixed it, so it reads differently."""
    element = etree.fromstring(b'<MoveToTreeID name="v" approach_tree="true"/>')
    step, _ = ontology.advance(ontology.State(), element)
    assert step.defect
    assert "has no id" in step.violation


def test_an_unknown_aisle_is_an_unknown_and_not_a_guess(orchard_map):
    """No orchard means the expectation cannot be bound, never that it failed.

    Every caller treats an unknown aisle as advice it cannot give. A number
    invented here would be a robot sent down the wrong lane.
    """
    element = etree.fromstring(b'<MoveToTreeID name="v" id="60" approach_tree="true"/>')
    without, _ = ontology.advance(ontology.State(), element)
    with_map, _ = ontology.advance(ontology.State(), element, orchard_map)
    assert without.needs[0].arg == ""
    assert with_map.needs[0].arg == "6"


def test_a_control_node_is_not_an_action():
    with pytest.raises(ontology.OntologyError):
        ontology.advance(ontology.State(), etree.fromstring(b"<Sequence/>"))


# ==========================================================================
# Fallback: only what every branch agrees on
# ==========================================================================


def test_a_choice_keeps_only_what_both_branches_establish():
    left = ontology.State(frozenset({ontology.Fact(ontology.AT_TREE, "10")}))
    right = ontology.State(frozenset({ontology.Fact(ontology.AT_TREE, "60")}))
    assert left.merge(right).facts == frozenset()
    assert left.merge(left).facts == left.facts


# ==========================================================================
# Pruning what has already happened
# ==========================================================================


def test_sample_leaf_trees_binds_names_to_ids(orchard_map):
    """The names /bt/status_change actually reports, resolved to tree ids."""
    got = ontology.sample_leaf_trees(example("aisle_sample_10_60.xml"), orchard_map)
    assert got == {"sample_tree10": "10", "sample_tree60": "60"}


def test_pruning_nothing_returns_the_plan_unchanged():
    plan = example("aisle_sample_10_60.xml")
    assert ontology.prune_completed(plan, set()) is plan


def test_a_completed_tree_and_its_retry_wrapper_are_removed(orchard_map):
    """Removing the objective must not leave an empty RetryUntilSuccessful.

    That is how every plan this fleet flies wraps a sample -- see
    PLANNER_PLANS above -- so a prune that only deleted the leaves would hand
    the model back a plan with a dangling, childless retry in it.
    """
    pruned = ontology.prune_completed(
        example("aisle_sample_10_60.xml"), {"10"}, orchard_map
    )
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"60"}
    assert pruned.find(".//RetryUntilSuccessful[@name='retry_tree10']") is None
    assert pruned.find(".//RetryUntilSuccessful[@name='retry_tree60']") is not None


def test_a_completed_trees_own_aisle_head_goes_with_it(orchard_map):
    """Tree 10's aisle (10) belongs to no other tree in this plan, so both its
    enter and exit MoveToAisleHead should go; tree 60's aisle (6) must stay."""
    pruned = ontology.prune_completed(
        example("aisle_sample_10_60.xml"), {"10"}, orchard_map
    )
    aisle_ids = [
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToAisleHead"
    ]
    assert aisle_ids == ["6", "6"]


def test_a_shared_aisle_head_survives_for_the_tree_still_pending():
    """Two trees in the same aisle: finishing one must not strand the other.

    A synthetic plan, because none of the real examples share an aisle -- the
    property this checks is that ``prune_completed`` looks at every remaining
    objective before deciding an aisle head is unneeded, not just the one
    being removed.
    """
    plan = etree.fromstring(
        b"<Sequence>"
        b'<MoveToAisleHead name="enter" id="6"/>'
        b'<MoveToTreeID name="v1" id="55" approach_tree="true"/>'
        b'<SampleLeaf name="sample_tree55"/>'
        b'<MoveToTreeID name="v2" id="60" approach_tree="true"/>'
        b'<SampleLeaf name="sample_tree60"/>'
        b'<MoveToAisleHead name="exit" id="6"/>'
        b"</Sequence>"
    )
    orchard_map = orchard.Orchard({55: 6, 60: 6})
    pruned = ontology.prune_completed(plan, {"55"}, orchard_map)
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"60"}
    aisle_heads = [el for el in ontology.actions_in(pruned) if el.tag == "MoveToAisleHead"]
    assert len(aisle_heads) == 2, "aisle 6 is still needed for tree 60"


def test_an_unknown_completed_tree_is_ignored(orchard_map):
    """A tree id that names nothing in the plan is not a defect to raise."""
    plan = example("aisle_sample_10_60.xml")
    pruned = ontology.prune_completed(plan, {"9999"}, orchard_map)
    remaining_ids = {
        el.get("id") for el in ontology.actions_in(pruned) if el.tag == "MoveToTreeID"
    }
    assert remaining_ids == {"10", "60"}


def _orchard_frame(name: str) -> str:
    """The orchard JSON out of a mission binary: length-prefixed frame two."""
    import struct

    with open(os.path.join(EXAMPLES, name), "rb") as handle:
        data = handle.read()
    offset = 0
    frames = []
    while offset + 4 <= len(data):
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        offset += 4
        frames.append(data[offset : offset + length])
        offset += length
    return frames[1].decode()
